version: '3.7'

services: 
  web: 
    build: .
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000  
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=
      - DEBUG=0
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
  db: 
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
